name: StockNewsSummarizer
channels:
  - apple
  - defaults
dependencies:
  - python=3.9
  - tensorflow-deps=2.9.0
  - pip:
      - beautifulsoup4==4.12.2
      - bs4==0.0.1
      - newsapi-python==0.2.7
      - tensorflow-macos==2.9.0
      - tensorflow-metal==0.5.0
      - transformers==4.20.1